version: "3"

services:
  cicd:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./log:/app/log
    ports:
      #<호스트 포트="">:<컨테이너 포트="">
      #docker run 시에는 안먹음
      #docker run -d -p 3001:3000
      - "3001:3000"
    restart: always
