version: "3.8"
services:
  sqlserver:
    image: "mcr.microsoft.com/azure-sql-edge"
    user: root
    container_name: sql1
    hostname: sql1
    ports:
      - 1433:1433
    volumes:
      - ./sql1data:/var/opt/mssql
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: password1!
